/**
 * Copyright 2011 The Open Source Research Group,
 *                University of Erlangen-Nürnberg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.sweble.wikitext.engine.ext.parser_functions;

import java.util.List;
import java.util.regex.Pattern;

import org.sweble.wikitext.engine.ExpansionFrame;
import org.sweble.wikitext.engine.config.WikiConfig;
import org.sweble.wikitext.engine.nodes.EngNode;
import org.sweble.wikitext.parser.nodes.WtNode;
import org.sweble.wikitext.parser.nodes.WtTemplate;
import org.sweble.wikitext.parser.nodes.WtText;

/**
 * <pre>
 * {{#iferror:
 *       test string
 *     | value if error
 *     | value if correct
 * }}
 * </pre>
 *
 * Like MediaWiki's <code>ParserFunctions::iferror()</code>, the test string
 * contains an error if it contains a <code>strong</code>, <code>span</code>,
 * <code>p</code> or <code>div</code> element with the class
 * <code>error</code>, as generated by other parser functions like
 * <code>#expr</code>. If no error occurred and there is no else branch, the
 * test string is returned.
 */
public class ParserFunctionIfError
		extends
			ParserFunctionsExtPfn.CtrlStmt
{
	private static final long serialVersionUID = 1L;

	/**
	 * The regular expression of MediaWiki's
	 * <code>ParserFunctions::iferror()</code>.
	 */
	private static final Pattern ERROR_RX = Pattern.compile(
			"<(?:strong|span|p|div)\\s(?:[^\\s>]*\\s+)*?class=\"(?:[^\"\\s>]*\\s+)*?error(?:\\s[^\">]*)?\"");

	/**
	 * Takes the place of tag extensions like MediaWiki's strip markers do.
	 */
	private static final char STRIP_MARKER = '\u007f';

	/**
	 * For un-marshaling only.
	 */
	public ParserFunctionIfError()
	{
		super("iferror");
	}

	public ParserFunctionIfError(WikiConfig wikiConfig)
	{
		super(wikiConfig, "iferror");
	}

	/**
	 * Like the strip markers MediaWiki passes on, nowiki in the test string
	 * must not be searched for errors.
	 */
	@Override
	protected boolean isNowikiKeptInFirstArgument()
	{
		return true;
	}

	@Override
	protected WtNode evaluate(
			WtTemplate pfn,
			ExpansionFrame frame,
			List<? extends WtNode> args)
	{
		if (args.size() < 1)
			return null;

		// The same instance is used by concurrent expansions: Keep all state
		// in local variables.
		WtNode test = frame.expand(args.get(0));

		if (containsError(test))
			return (args.size() > 1) ? args.get(1) : null;

		// If NO error occurred and there is no else branch, the test string
		// becomes the result.
		return (args.size() > 2) ? args.get(2) : test;
	}

	private static boolean containsError(WtNode test)
	{
		StringBuilder text = new StringBuilder();
		if (collectText(test, text))
			return true;

		return ERROR_RX.matcher(text).find();
	}

	/**
	 * Collects the text of the expanded test string.
	 *
	 * @return True if a soft error node was found, which is rendered as
	 *         <code>&lt;strong class="error"&gt;</code>.
	 */
	private static boolean collectText(WtNode node, StringBuilder text)
	{
		if (node.getNodeType() == EngNode.NT_SOFT_ERROR)
			return true;

		if (node.getNodeType() == WtNode.NT_TEXT)
		{
			text.append(((WtText) node).getContent());
		}
		else if (node.getNodeType() == WtNode.NT_TAG_EXTENSION
				|| node.getNodeType() == EngNode.NT_NOWIKI)
		{
			// The content of tag extensions and nowiki is not searched
			text.append(STRIP_MARKER);
		}
		else
		{
			for (WtNode n : node)
			{
				if (collectText(n, text))
					return true;
			}
		}

		return false;
	}
}
