/**
 * Copyright 2011 The Open Source Research Group,
 *                University of Erlangen-Nürnberg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.sweble.wikitext.engine.ext.convert;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 * Generates the unit data used by {@link Convert} from the source of
 * <a href="https://en.wikipedia.org/wiki/Module:Convert/data">Module:Convert/data</a>.
 *
 * <p>
 * Usage (after building the test classes of swc-engine, in its directory):
 *
 * <pre>
 * curl -o data.lua 'https://en.wikipedia.org/w/index.php?title=Module:Convert/data&amp;action=raw'
 * java -cp target/classes:target/test-classes \
 *     org.sweble.wikitext.engine.ext.convert.ConvertDataGenerator \
 *     data.lua ../swc-convert-data/src/main/resources/org/sweble/wikitext/convert-data/convert-data.txt REVISION
 * </pre>
 *
 * <p>
 * The output is derived from Wikipedia and licensed under CC BY-SA 4.0, which
 * is why it lives in the separate artifact swc-convert-data. Update the
 * revision in its NOTICE file as well.
 *
 * <p>
 * Module:Convert/data is itself generated and only contains Lua table
 * constructors, so a small parser for that subset of Lua is sufficient. The
 * output format is read by {@link ConvertData}: a section header like
 * "[all_units]" is followed by one entry per line whose fields are separated by
 * tabs. Lists are separated by "|" and the subdivisions of a unit are written
 * as "code:count:default[:unit]".
 */
public final class ConvertDataGenerator
{
	private static final String[] SECTIONS = {
			"all_units",
			"default_exceptions",
			"link_exceptions",
			"per_unit_fixups" };

	private ConvertDataGenerator()
	{
	}

	public static void main(String[] args) throws IOException
	{
		if (args.length < 2)
		{
			System.err.println("Usage: ConvertDataGenerator DATA.lua OUTPUT [REVISION]");
			System.exit(1);
		}
		String lua = new String(Files.readAllBytes(Paths.get(args[0])), StandardCharsets.UTF_8);
		String revision = (args.length > 2) ? args[2] : null;
		try (Writer w = Files.newBufferedWriter(Paths.get(args[1]), StandardCharsets.UTF_8))
		{
			w.write(generate(lua, revision));
		}
	}

	/**
	 * @param lua The source of Module:Convert/data.
	 * @param revision The revision of the source or null.
	 * @return The content of the data file.
	 */
	static String generate(String lua, String revision)
	{
		Map<String, Object> tables = new LuaParser(lua).parseChunk();

		// Attribution of the source (CC BY-SA 4.0); the file is excluded from
		// the license header check
		StringBuilder sb = new StringBuilder();
		sb.append("#\n");
		sb.append("# Unit data of {{convert}}, derived from\n");
		sb.append("# https://en.wikipedia.org/wiki/Module:Convert/data");
		if (revision != null)
		{
			sb.append(" (revision ").append(revision).append(')');
		}
		sb.append("\n");
		sb.append("# by the Wikipedia contributors. The source is licensed under the Creative\n");
		sb.append("# Commons Attribution-ShareAlike 4.0 International License\n");
		sb.append("# (https://creativecommons.org/licenses/by-sa/4.0/). The authors are listed\n");
		sb.append("# in the page history:\n");
		sb.append("# https://en.wikipedia.org/w/index.php?title=Module:Convert/data&action=history\n");
		sb.append("#\n");
		sb.append("# Generated by ConvertDataGenerator. Do not edit this file, run the\n");
		sb.append("# generator instead.\n");
		sb.append("#\n");

		for (String section : SECTIONS)
		{
			Object table = tables.get(section);
			if (!(table instanceof LuaTable))
			{
				throw new IllegalArgumentException("Missing table " + section);
			}
			sb.append('[').append(section).append("]\n");
			for (Entry<Object, Object> e : ((LuaTable) table).entries())
			{
				sb.append(checkKey((String) e.getKey()));
				Object value = e.getValue();
				if (value instanceof LuaTable)
				{
					for (Entry<Object, Object> field : ((LuaTable) value).entries())
					{
						String key = (String) field.getKey();
						sb.append('\t').append(check(key)).append('=')
								.append(check(fieldValue(key, field.getValue())));
					}
				}
				else if (section.equals("per_unit_fixups"))
				{
					// A string gives the unit type.
					sb.append("\tutype=").append(check(scalar(value)));
				}
				else
				{
					sb.append('\t').append(check(scalar(value)));
				}
				sb.append('\n');
			}
		}
		return sb.toString();
	}

	private static String fieldValue(String key, Object value)
	{
		if (!(value instanceof LuaTable))
		{
			return scalar(value);
		}
		LuaTable table = (LuaTable) value;
		StringBuilder sb = new StringBuilder();
		if (key.equals("subdivs"))
		{
			for (Entry<Object, Object> e : table.entries())
			{
				LuaTable subdiv = (LuaTable) e.getValue();
				if (sb.length() > 0)
				{
					sb.append('|');
				}
				sb.append(listItem((String) e.getKey())).append(':')
						.append(scalar(subdiv.get(1d))).append(':')
						.append(listItem(scalar(subdiv.get("default"))));
				if (subdiv.get("unit") != null)
				{
					sb.append(':').append(listItem(scalar(subdiv.get("unit"))));
				}
				if (subdiv.get("name") != null)
				{
					throw new IllegalArgumentException("Unsupported subdivision name");
				}
			}
			return sb.toString();
		}
		for (int i = 1; i <= table.size(); i++)
		{
			Object item = table.get((double) i);
			if (item == null || item instanceof LuaTable)
			{
				throw new IllegalArgumentException("Unsupported list " + key);
			}
			if (i > 1)
			{
				sb.append('|');
			}
			sb.append(listItem(scalar(item)));
		}
		if (table.size() != table.entries().size())
		{
			throw new IllegalArgumentException("Unsupported table " + key);
		}
		return sb.toString();
	}

	private static String scalar(Object value)
	{
		if (value instanceof LuaNumber)
		{
			return ((LuaNumber) value).text;
		}
		if (value instanceof String || value instanceof Boolean)
		{
			return value.toString();
		}
		throw new IllegalArgumentException("Unsupported value " + value);
	}

	private static String listItem(String item)
	{
		if (item.indexOf('|') >= 0 || item.indexOf(':') >= 0)
		{
			throw new IllegalArgumentException("Unsupported list item " + item);
		}
		return item;
	}

	private static String check(String text)
	{
		if (text.indexOf('\t') >= 0 || text.indexOf('\n') >= 0 || text.indexOf('\r') >= 0)
		{
			throw new IllegalArgumentException("Unsupported text " + text);
		}
		return text;
	}

	private static String checkKey(String key)
	{
		if (key.isEmpty() || key.startsWith("[") || key.startsWith("#"))
		{
			throw new IllegalArgumentException("Unsupported key " + key);
		}
		return check(key);
	}

	// =========================================================================

	/**
	 * A number with the text used in the source (e.g. "0.3048"). Values
	 * given as an expression (e.g. "32-273.15*(9/5)") are evaluated.
	 */
	static final class LuaNumber
	{
		final double value;

		final String text;

		LuaNumber(double value, String text)
		{
			this.value = value;
			this.text = text;
		}

		@Override
		public String toString()
		{
			return text;
		}
	}

	/**
	 * A Lua table with the keys in source order. Numeric keys are doubles.
	 */
	static final class LuaTable
	{
		private final Map<Object, Object> map = new LinkedHashMap<Object, Object>();

		private int size;

		void add(Object value)
		{
			map.put((double) ++size, value);
		}

		void put(Object key, Object value)
		{
			map.put(key, value);
		}

		Object get(Object key)
		{
			return map.get(key);
		}

		/** @return The number of positional values. */
		int size()
		{
			return size;
		}

		List<Entry<Object, Object>> entries()
		{
			return new ArrayList<Entry<Object, Object>>(map.entrySet());
		}
	}

	/**
	 * Parses the statements "local name = value" and "return value" where each
	 * value is a table constructor, a string, a boolean or an arithmetic
	 * expression of numbers.
	 */
	static final class LuaParser
	{
		private final String src;

		private int pos;

		LuaParser(String src)
		{
			this.src = src;
		}

		Map<String, Object> parseChunk()
		{
			Map<String, Object> result = new LinkedHashMap<String, Object>();
			while (true)
			{
				skipSpace();
				if (pos >= src.length())
				{
					return result;
				}
				if (keyword("local"))
				{
					String name = name();
					expect('=');
					result.put(name, value());
				}
				else if (keyword("return"))
				{
					value();
				}
				else
				{
					throw error("Statement expected");
				}
			}
		}

		private boolean keyword(String word)
		{
			if (src.startsWith(word, pos)
					&& (pos + word.length() >= src.length()
					|| !isNameChar(src.charAt(pos + word.length()))))
			{
				pos += word.length();
				return true;
			}
			return false;
		}

		private static boolean isNameChar(char c)
		{
			return Character.isLetterOrDigit(c) || c == '_';
		}

		private String name()
		{
			skipSpace();
			int start = pos;
			while (pos < src.length() && isNameChar(src.charAt(pos)))
			{
				pos++;
			}
			if (start == pos)
			{
				throw error("Name expected");
			}
			return src.substring(start, pos);
		}

		private void expect(char c)
		{
			skipSpace();
			if (pos >= src.length() || src.charAt(pos) != c)
			{
				throw error("'" + c + "' expected");
			}
			pos++;
		}

		private boolean accept(char c)
		{
			skipSpace();
			if (pos < src.length() && src.charAt(pos) == c)
			{
				pos++;
				return true;
			}
			return false;
		}

		private Object value()
		{
			skipSpace();
			char c = src.charAt(pos);
			if (c == '{')
			{
				return table();
			}
			if (c == '"' || c == '\'')
			{
				return string();
			}
			if (keyword("true"))
			{
				return Boolean.TRUE;
			}
			if (keyword("false"))
			{
				return Boolean.FALSE;
			}
			if (Character.isLetter(c) || c == '_')
			{
				// a reference to a table defined before (in the return statement)
				return name();
			}
			int start = pos;
			double value = expression();
			String text = src.substring(start, pos).trim();
			if (!text.matches("-?(\\d+\\.?\\d*|\\.\\d+)([eE][-+]?\\d+)?"))
			{
				text = Double.toString(value);
			}
			return new LuaNumber(value, text);
		}

		private LuaTable table()
		{
			expect('{');
			LuaTable table = new LuaTable();
			while (!accept('}'))
			{
				skipSpace();
				if (accept('['))
				{
					Object key = value();
					if (key instanceof LuaNumber)
					{
						key = ((LuaNumber) key).value;
					}
					expect(']');
					expect('=');
					table.put(key, value());
				}
				else if (isFieldName())
				{
					String key = name();
					expect('=');
					table.put(key, value());
				}
				else
				{
					table.add(value());
				}
				if (!accept(','))
				{
					accept(';');
				}
			}
			return table;
		}

		private boolean isFieldName()
		{
			int p = pos;
			if (p >= src.length() || !(Character.isLetter(src.charAt(p)) || src.charAt(p) == '_'))
			{
				return false;
			}
			while (p < src.length() && isNameChar(src.charAt(p)))
			{
				p++;
			}
			while (p < src.length() && Character.isWhitespace(src.charAt(p)))
			{
				p++;
			}
			return p + 1 < src.length() && src.charAt(p) == '=' && src.charAt(p + 1) != '=';
		}

		private String string()
		{
			char quote = src.charAt(pos++);
			StringBuilder sb = new StringBuilder();
			while (true)
			{
				char c = src.charAt(pos++);
				if (c == quote)
				{
					return sb.toString();
				}
				if (c == '\n')
				{
					throw error("Unfinished string");
				}
				if (c == '\\')
				{
					c = src.charAt(pos++);
					switch (c)
					{
						case 'n':
							sb.append('\n');
							break;
						case 't':
							sb.append('\t');
							break;
						default:
							if (Character.isDigit(c))
							{
								throw error("Unsupported escape");
							}
							sb.append(c);
					}
				}
				else
				{
					sb.append(c);
				}
			}
		}

		// expression = term { ("+" | "-") term }
		private double expression()
		{
			double value = term();
			while (true)
			{
				if (accept('+'))
				{
					value += term();
				}
				else if (peekMinus())
				{
					pos++;
					value -= term();
				}
				else
				{
					return value;
				}
			}
		}

		private boolean peekMinus()
		{
			skipSpace();
			return pos < src.length() && src.charAt(pos) == '-' && !src.startsWith("--", pos);
		}

		// term = unary { ("*" | "/") unary }
		private double term()
		{
			double value = unary();
			while (true)
			{
				if (accept('*'))
				{
					value *= unary();
				}
				else if (accept('/'))
				{
					value /= unary();
				}
				else
				{
					return value;
				}
			}
		}

		// unary = "-" unary | power
		private double unary()
		{
			if (peekMinus())
			{
				pos++;
				return -unary();
			}
			return power();
		}

		// power = primary [ "^" unary ]
		private double power()
		{
			double value = primary();
			if (accept('^'))
			{
				return Math.pow(value, unary());
			}
			return value;
		}

		private double primary()
		{
			if (accept('('))
			{
				double value = expression();
				expect(')');
				return value;
			}
			skipSpace();
			int start = pos;
			while (pos < src.length())
			{
				char c = src.charAt(pos);
				if (Character.isDigit(c) || c == '.')
				{
					pos++;
				}
				else if ((c == 'e' || c == 'E') && pos > start)
				{
					pos++;
					if (pos < src.length() && (src.charAt(pos) == '-' || src.charAt(pos) == '+'))
					{
						pos++;
					}
				}
				else
				{
					break;
				}
			}
			if (start == pos)
			{
				throw error("Number expected");
			}
			return Double.parseDouble(src.substring(start, pos));
		}

		private void skipSpace()
		{
			while (pos < src.length())
			{
				char c = src.charAt(pos);
				if (Character.isWhitespace(c))
				{
					pos++;
				}
				else if (src.startsWith("--[[", pos))
				{
					int end = src.indexOf("]]", pos);
					pos = (end < 0) ? src.length() : end + 2;
				}
				else if (src.startsWith("--", pos))
				{
					int end = src.indexOf('\n', pos);
					pos = (end < 0) ? src.length() : end + 1;
				}
				else
				{
					break;
				}
			}
		}

		private IllegalArgumentException error(String message)
		{
			int line = 1;
			for (int i = 0; i < pos && i < src.length(); i++)
			{
				if (src.charAt(i) == '\n')
				{
					line++;
				}
			}
			return new IllegalArgumentException(message + " in line " + line);
		}
	}
}
